# -*- coding: utf-8 -*-
"""data_processing_knh.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WZC1H_VzObJ1dkj8oWLo52XN4e-JJzop

# 드라이브 불러오기
"""

from google.colab import drive
drive.mount('/content/drive')

"""# 데이터 파일 불러오기"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MultiLabelBinarizer
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/track_data_final.csv")
print(df.shape)
df.head(5)

"""# 1. 날짜 처리"""

df['album_release_date'] = pd.to_datetime(df['album_release_date'], errors='coerce')
df['release_year'] = df['album_release_date'].dt.year
df['release_month'] = df['album_release_date'].dt.month
df['release_quarter'] = df['album_release_date'].dt.quarter

# 연도 행 범위 계산
min_year = df['release_year'].min()
max_year = df['release_year'].max()
print(f"연도 행 범위: {min_year} ~ {max_year}")

# 데이터 개수가 적은 1952~2008년 사이 행 제거
df = df[~df['release_year'].between(1952, 2008)]

# 제거 후 연도 범위 확인
min_year = df['release_year'].min()
max_year = df['release_year'].max()
print(f"제거 후 연도 행 범위: {min_year} ~ {max_year}")

"""# 2. 장르 처리"""

# 문자열 형태의 장르 → 리스트 변환
df['artist_genres_list'] = df['artist_genres'].apply(lambda x: eval(x) if pd.notnull(x) else [])

# 빈 리스트 제거
df = df[df['artist_genres_list'].map(len) > 0]

# Multi-hot encoding
mlb = MultiLabelBinarizer()
genre_encoded = mlb.fit_transform(df['artist_genres_list'])
genre_df = pd.DataFrame(genre_encoded, columns=mlb.classes_, index=df.index)

# 기존 장르 컬럼 제거 (중복 방지)
for col in mlb.classes_:
    if col in df.columns:
        df.drop(columns=col, inplace=True)

# 인코딩된 장르 컬럼 합치기
df = pd.concat([df, genre_df], axis=1)

# 총 장르 개수 확인
print(f"총 장르 개수: {len(mlb.classes_)}개")

# 전체 장르 분포 확인
genre_counts = df[mlb.classes_].sum().sort_values(ascending=False)
print("\n장르별 총합:")
print(genre_counts.head(10))

"""# 3. 아티스트 영향력 변수 생성"""

df['followers_log'] = np.log1p(df['artist_followers'])

"""# 4. 히트곡 라벨 생성"""

# track_popularity 기준 히트곡 라벨 생성. 상위 10% 곡을 hit로 설정
threshold = df['track_popularity'].quantile(0.9)
df['hit'] = (df['track_popularity'] >= threshold).astype(int)

# 히트곡과 비히트곡 개수 출력
hit_counts = df['hit'].value_counts()
print("히트곡(1)과 비히트곡(0) 개수:")
print(hit_counts)

df.head(5)

"""# 결과 확인"""

# 전처리 완료 후 파일 저장 경로
output_path = "/content/drive/MyDrive/Colab Notebooks/spotify_preprocessed.csv"

# CSV로 저장 (인덱스는 저장하지 않음)
df.to_csv(output_path, index=False)

print(f"전처리 완료 파일 저장됨: {output_path}")