# -*- coding: utf-8 -*-
"""Feat. SVM

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zJgrHo6KQ0Bl2QpwV8rDXKR24-TvtqzT

## 드라이브 불러오기 ##
"""

from google.colab import drive
drive.mount('/content/drive')

"""## 데이터 파일 불러오기 및 필요한 라이브러리 임포트##"""

from google.colab import files
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, StratifiedKFold, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    classification_report, confusion_matrix, roc_auc_score,
    RocCurveDisplay, PrecisionRecallDisplay
)
from sklearn.pipeline import Pipeline
df=pd.read_csv('/content/drive/MyDrive/aiai/spotify_top_songs_audio_features.csv')

"""데이터셋 중복 제거"""

# 완전 중복 행 개수 확인
dup_all = df.duplicated().sum()
print("완전히 동일한 중복 행 개수:", dup_all)

# 완전 중복 행 제거
if dup_all > 0:
    df = df.drop_duplicates().reset_index(drop=True)
    print("중복 제거 후 데이터 형태:", df.shape)
else:
    print("완전 중복 행은 없습니다.")

"""#결측치제거

인공지능 모델 학습에서 필요한 주요 열들에 대한 정보가 없다면 정확한 노래 분석이 불가능.
그러므로 결측치 존재하는 행은 제거.

--> 해당 데이터셋은 분석이 불가능한 행이 존재하지 않음.
"""

# (3) 결측치 상황 확인
print("\n[컬럼별 결측치 개수]")
print(df.isna().sum())

# (4) 우리가 꼭 쓸 컬럼들 중 결측치가 있으면 행 제거
required_cols = [
    "streams", "weeks_on_chart",
    "danceability", "energy", "speechiness", "acousticness",
    "instrumentalness", "liveness", "valence",
    "loudness", "tempo", "duration_ms",
    "key", "mode", "time_signature"
]

# 위 컬럼들 중 하나라도 NaN이면 그 행은 드롭
before_drop = df.shape[0]
df = df.dropna(subset=required_cols).reset_index(drop=True)
after_drop = df.shape[0]

print(f"\n결측치 제거 전 행 개수: {before_drop}")
print(f"결측치 제거 후 행 개수: {after_drop}")
print(f"제거된 행 수: {before_drop - after_drop}")

"""지도학습을 위한 'hit' 레이블 생성
 - streams : 단순히 "얼마나 많이 들었나"를 보여줌
 - weeks_on_chart : "얼마나 오래 사랑받았는가"
 결론적으로 두가지 열을 합쳐서 새로운 열을 만드는 것이 타당하다고 판단. 방법은?

예를 들어.. 3억번 스트리밍 + 15주간 차트인
300,000,000 + 15는 두 열의 특성을 살리기 힘들다.
1. streams 로그 변환
 - 오른쪽 꼬리가 매우 긴 분포
 - 10배씩 커질 때 log 값이 1씩 증가
2. z-score로 "같은 기준선" 만들기
 - 정규화로 표준편차로 이용하기
3. 두 z-score의 평균으로 hit_score 생성
"""

# 기본 정보 확인
print(df.shape)      # (행 개수, 열 개수)
print(df.columns)    # 컬럼 이름들
df.head()

# 스트리밍 수, 차트 잔류 주 수 통계 확인
print(df["streams"].describe())
print(df["weeks_on_chart"].describe())

"""hit레이블 생성 코드"""

# 1) 로그 변환
df["log_streams"] = np.log10(df["streams"])

df[["streams", "log_streams"]].head()

# 2) log_streams, weeks_on_chart 각각 z-score로 표준화
# 해석 참고 : z-socore이 0보다 큰 경우 평균보다 스트리밍이 많고 차트에 오래 있었음.

df["streams_z"] = (df["log_streams"] - df["log_streams"].mean()) / df["log_streams"].std()
df["weeks_z"]   = (df["weeks_on_chart"] - df["weeks_on_chart"].mean()) / df["weeks_on_chart"].std()

df[["log_streams", "streams_z", "weeks_on_chart", "weeks_z"]].head()

# 3) 두 z-score의 평균으로 hit_score 정의

# 두가지 z-score의 평균으로 메가 히트곡(feat.베스트셀러)을 찾기 위한 레이블 정의

df["hit_score"] = (df["streams_z"] + df["weeks_z"]) / 2

df[["streams_z", "weeks_z", "hit_score"]].head()

"""**그렇다면!!**
어떤 곡들을 hit레이블에 해당시킬건가?

--> 가장 직관적이고 대중적인 ***상위 10%*** 를 메가 히트곡으로 정의. --> hit 레이블에 1로 설정.
"""

# 1) 메가 히트 비율 설정 (상위 15%)
top_ratio = 0.10     # 나중에 0.10, 0.20 등으로 바꿔가며 실험 가능
q = 1 - top_ratio    # 예: 0.85 분위수

# 2) hit_score 기준값(threshold) 계산
threshold = df["hit_score"].quantile(q)

print("=== hit_score 기준 정보 ===")
print(f"상위 비율 (top_ratio): {top_ratio*100:.1f}%")
print(f"사용한 분위수 (q): {q:.2f}")
print(f"hit_score threshold 값: {threshold:.4f}")

# 3) threshold 이상이면 hit=1, 미만이면 hit=0
df["hit"] = (df["hit_score"] >= threshold).astype(int)

# 4) 라벨 개수/비율 확인
print("\n=== hit 라벨 분포(개수) ===")
print(df["hit"].value_counts())

print("\n=== hit 라벨 분포(비율) ===")
print(df["hit"].value_counts(normalize=True))

# 5) hit_score 기준 상위 몇 곡 예시로 확인
print("\n=== hit_score 상위 10곡 예시 ===")
print(
    df[["track_name", "artist_names", "hit_score", "streams", "weeks_on_chart", "hit"]]
    .sort_values("hit_score", ascending=False)
    .head(10)
)

"""hit 레이블이 포함된 학습 준비용 csv파일"""

# 현재 df 전체(원본 + hit_score + hit 포함)를 새 CSV로 저장
output_path = "spotify_top_songs_with_hit.csv"

df.to_csv(output_path, index=False)

print("저장 완료:", output_path)

"""전처리 후 CSV 파일 불러오기 및 기본 정보 재확인"""

df = pd.read_csv("spotify_top_songs_with_hit.csv")
print(df.shape)
print(df.columns)
df.head()

# 우리가 hit 비율을 상위 10프로로 설정했기에 재확인
# 학습 데이터셋에서 메가히트곡은 상위 10%의 곡을 말함
print(df["hit"].value_counts())
print(df["hit"].value_counts(normalize=True))

"""SVM용 X,y 정의
- 숫자형 feature과 범주형 feature를 구분하는 작업
"""

# hit 레이블은 y
y = df["hit"]

# 숫자형 오디오 feature
num_cols = [
    "danceability", "energy", "speechiness", "acousticness",
    "instrumentalness", "liveness", "valence",
    "loudness", "tempo", "duration_ms"
]

# 범주형 feature (문자열)
cat_cols = ["key", "mode", "time_signature"]

# 입력 X는 두 종류를 합친 원본 형태
X = df[num_cols + cat_cols].copy()

print(X.dtypes)

"""ColumnTransformer
- feature별로 다른 전처리를 적용

스케일링 단계
1. 문제
- 현재 feature마다 값 범위가 제각각임
- 값 범위가 큰 feature가 영향을 훨씬 많이 줘버림
2. 해결방법
- 각 feature를 "평균 0, 표준편차 1"로 표준화
- 모든 축이 비슷한 스케일이 되도록 함

범주형 OneHotEncoder
- 범주형 변수를 0/1벡터로 변경
- 예 : mode -> mode_major, mode_minor
"""

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

# 숫자형에는 StandardScaler, 범주형에는 OneHotEncoder
preprocess = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), num_cols),                   # 숫자형 처리

        # handle_unknown="ignore"은 train에 없었던 카테고리가 test에 나와도
        # 에러 대신 그냥 그 카테고리는 전부 0으로 처리
        ("cat", OneHotEncoder(handle_unknown="ignore"), cat_cols)  # 범주형 처리
    ]
)

"""SVM 설정 단계
- RBF 커널은 비선형 경계를 만들 수 있게 해줌
- feature가 여러개이기에 단순한 직선 혹은 평면 구조가 아닐 것이라고 예측
- hit의 비율은 10%. 즉, 전부 0이라고 예측해도 무려 정확도가 90%에 달함. "class_weight="balanced""를 통해 히트곡을 더 중요하게 학습하도록 유도
"""

svm_clf = Pipeline(steps=[
    ("preprocess", preprocess),      # 1) 컬럼별 전처리
    ("svm", SVC(
        kernel="rbf",
        class_weight="balanced",
        probability=True,
        random_state=42
    ))                               # 2) SVM 분류기
])

X_train, X_test, y_train, y_test = train_test_split(
    X, y,

    # test 데이터 비율을 20%로 설정
    test_size=0.2,
    random_state=42,

    # train에서도 test에서도 hit 비율을 10프로로 유지
    stratify=y
)

preprocess.fit(X_train)

X_train_trans = preprocess.transform(X_train)
X_test_trans  = preprocess.transform(X_test)

print("전처리 후 X_train shape:", X_train_trans.shape)
print("전처리 후 X_test  shape:", X_test_trans.shape)

# 숫자형 feature 이름
num_features = num_cols

# 범주형에서 원-핫으로 생긴 feature 이름
cat_features = preprocess.named_transformers_["cat"].get_feature_names_out(cat_cols)

all_feature_names = list(num_features) + list(cat_features)

print(len(all_feature_names))
print(all_feature_names[:28])  # 앞쪽 몇 개만 확인

"""베이스 SVM 학습 & 평가"""

svm_clf.fit(X_train, y_train)

# 예측
y_pred_base = svm_clf.predict(X_test)

print("=== Baseline SVM (ColumnTransformer 버전) ===")
print("Accuracy :", accuracy_score(y_test, y_pred_base))
print("F1-score :", f1_score(y_test, y_pred_base))
print("\n[Classification Report]")
print(classification_report(y_test, y_pred_base))

"""1차 학습 결과 요약

HIT = 0, 히트곡 예측 성능
- 해당 SVM은 히트곡을 절반 정도는 찾아냈지만
히트곡이라고 결론지은 대부분의 곡은 실제로 아닐 확률이 높다.

HIT = 1, 히트곡 제외곡 예측 성능
- 일반곡을 60프로 정도 맞출 수 있고 일반곡이라고 예측한 것들은 대부분 진짜 예측곡일 확률이 높다.

최종 정확도에서 단순히 맞춘 비율은 59%정도 이나 히트곡을 맞출 정확도는 더 떨어지는 상태

## 우리의 목표는 히트곡을 얼마나 더 잘 찾을것인가 ##
이기에 HIT = 1의 F1과 RECALL을 더 신경써야함.

문제점 복기

1. Precision(hit=1)이 너무 낮음
- 히트곡일 거라고 예상한 곡들 중 진짜 히트곡은 10%대에 불과

2. accuracy가 0.59로 객관적으로 너무 낮음

##숫자형 feature SVM 구현

범주형 feature들은 데이터셋 상에서 다양화되어있지 않음. 추가적으로 one-hot 인코딩이 "잡음"으로 작용했을 가능성도 있다고 판단.
"""

# 1) 숫자형 feature만 선택
num_cols = [
    "danceability", "energy", "speechiness", "acousticness",
    "instrumentalness", "liveness", "valence",
    "loudness", "tempo", "duration_ms"
]

X_num = df[num_cols].copy()
y = df["hit"]

# 2) train/test split
X_train, X_test, y_train, y_test = train_test_split(
    X_num, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# 3) 스케일링 + SVM 파이프라인
svm_num = Pipeline([
    ("scaler", StandardScaler()),
    ("svm", SVC(
        kernel="rbf",
        class_weight="balanced",
        probability=True,
        random_state=42
    ))
])

# 4) 학습 & 평가
svm_num.fit(X_train, y_train)
y_pred_num = svm_num.predict(X_test)

print("=== SVM (숫자형 feature만 사용) ===")
print("Accuracy :", accuracy_score(y_test, y_pred_num))
print("F1-score :", f1_score(y_test, y_pred_num))
print("\n[Classification Report]")
print(classification_report(y_test, y_pred_num))

"""숫자형 feature만을 이용한 SVM 학습 결과

- 이전과 비슷하거나 아주 조금 더 낮은 정확도를 보임
- random_state가 같기에 test데이터는 동일조건

다른 의미로.. 범주형 feature가 "엄청 중요" 보다는 어느 정도 기여를 하고 있다는 정보는 얻을 수 있음

그러므로 1차 머신 러닝에서 더 발전시켜 보기로 함

##발전 1단계. GridSearchCV로 C, gamma 튜닝 세팅

1. C : 오차를 얼마나 허용할 것인가
- 높다면 훈련데이터에 더 집착하고 경계가 복잡
- 낮다면 부드러운 경계

2. gamma (RBF폭)
- 높다면 영향이 매우 좁아서 경계가 많이 휘어짐
- 낮다면 넓게 퍼져서 부드러운 경계
"""

num_cols = [
    "danceability", "energy", "speechiness", "acousticness",
    "instrumentalness", "liveness", "valence",
    "loudness", "tempo", "duration_ms"
]
cat_cols = ["key", "mode", "time_signature"]

X = df[num_cols + cat_cols].copy()
y = df["hit"]

preprocess = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), num_cols),
        ("cat", OneHotEncoder(handle_unknown="ignore"), cat_cols)
    ]
)

svm_clf = Pipeline(steps=[
    ("preprocess", preprocess),
    ("svm", SVC(
        kernel="rbf",
        class_weight="balanced",
        probability=True,
        random_state=42
    ))
])

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# 값 범위는 전형적인 로그 스케일.
param_grid = {
    "svm__C":     [0.1, 1, 10, 100],
    "svm__gamma": [0.01, 0.1, 1],
    "svm__kernel": ["rbf"],
}

# 매 fold마다 히트 10%/비히트 90% 구조를 유지.
# 데이터를 5조각으로 나누어서 4조각은 학습 1조각은 검증
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

grid_svm = GridSearchCV(
    estimator=svm_clf,      # ColumnTransformer 포함된 전체 파이프라인
    param_grid=param_grid,
    scoring="f1",           # hit=1 기준 F1-score를 기준으로 최적화
    cv=cv,
    n_jobs=-1,              # 가능한 모든 코어 사용
    verbose=1
)

# 각 (C, gamma) 조합에 대해 평균 F1이 가장 좋은 조합을 선택
grid_svm.fit(X_train, y_train)

print("=== Best Params (SVM) ===")
print(grid_svm.best_params_)
print("Best CV F1-score:", grid_svm.best_score_)

"""##발전 2단계. 최적 파라미터를 이용한 최적 SVM으로 최종 평가"""

best_svm = grid_svm.best_estimator_

y_pred = best_svm.predict(X_test)
y_proba = best_svm.predict_proba(X_test)[:, 1]   # hit=1 확률

acc   = accuracy_score(y_test, y_pred)
prec1 = precision_score(y_test, y_pred)      # default pos_label=1
rec1  = recall_score(y_test, y_pred)
f1_1  = f1_score(y_test, y_pred)
auc   = roc_auc_score(y_test, y_proba)

print("=== Tuned SVM (GridSearch 후) ===")
print("Accuracy :", acc)
print("Precision(1):", prec1)
print("Recall(1)   :", rec1)
print("F1(1)       :", f1_1)
print("ROC-AUC     :", auc)

print("\n[Classification Report]")
print(classification_report(y_test, y_pred))

"""임시 결론.
## 기존 SVM과 큰 성능 차이가 거의 없다. 사실상 오차범위 수준이라고 봐도 무방하다.

- hit 레이블의 신뢰도 문제.
- 오디오 feature 만으로 설명 안되는 요인 --> 정보화 시대에서는 크게 작용하는 듯함.
- 외부요인이 크게 작용한다는 것을 반증하듯 최적의 파라미터에서도 f1이 유의미한 변화를 보이지 않음.

발전 방향.
- 다른 모델의 결과 여부
- feature 확장 필요성 대두
"""