# -*- coding: utf-8 -*-
"""data_reforming_ysh.ipynb의 사본

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1co-HmlR3DdiGV6iB_qy2LnZLG5H7YRkO

## 드라이브 불러오기 ##
"""

from google.colab import drive
drive.mount('/content/drive')

"""## 데이터 파일 불러오기 ##"""

from google.colab import files
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv('/content/drive/MyDrive/aiai/spotify_top_songs_audio_features.csv')

"""데이터셋 중복 제거"""

# 완전 중복 행 개수 확인
dup_all = df.duplicated().sum()
print("완전히 동일한 중복 행 개수:", dup_all)

# 완전 중복 행 제거
if dup_all > 0:
    df = df.drop_duplicates().reset_index(drop=True)
    print("중복 제거 후 데이터 형태:", df.shape)
else:
    print("완전 중복 행은 없습니다.")

"""#결측치제거

인공지능 모델 학습에서 필요한 주요 열들에 대한 정보가 없다면 정확한 노래 분석이 불가능.
그러므로 결측치 존재하는 행은 제거.

--> 해당 데이터셋은 분석이 불가능한 행이 존재하지 않음.
"""

# (3) 결측치 상황 확인
print("\n[컬럼별 결측치 개수]")
print(df.isna().sum())

# (4) 우리가 꼭 쓸 컬럼들 중 결측치가 있으면 행 제거
required_cols = [
    "streams", "weeks_on_chart",
    "danceability", "energy", "speechiness", "acousticness",
    "instrumentalness", "liveness", "valence",
    "loudness", "tempo", "duration_ms",
    "key", "mode", "time_signature"
]

# 위 컬럼들 중 하나라도 NaN이면 그 행은 드롭
before_drop = df.shape[0]
df = df.dropna(subset=required_cols).reset_index(drop=True)
after_drop = df.shape[0]

print(f"\n결측치 제거 전 행 개수: {before_drop}")
print(f"결측치 제거 후 행 개수: {after_drop}")
print(f"제거된 행 수: {before_drop - after_drop}")

"""지도학습을 위한 'hit' 레이블 생성
 - streams : 단순히 "얼마나 많이 들었나"를 보여줌
 - weeks_on_chart : "얼마나 오래 사랑받았는가"
 결론적으로 두가지 열을 합쳐서 새로운 열을 만드는 것이 타당하다고 판단. 방법은?

예를 들어.. 3억번 스트리밍 + 15주간 차트인
300,000,000 + 15는 두 열의 특성을 살리기 힘들다.
1. streams 로그 변환
 - 오른쪽 꼬리가 매우 긴 분포
 - 10배씩 커질 때 log 값이 1씩 증가
2. z-score로 "같은 기준선" 만들기
 - 정규화로 표준편차로 이용하기
3. 두 z-score의 평균으로 hit_score 생성
"""

# 기본 정보 확인
print(df.shape)      # (행 개수, 열 개수)
print(df.columns)    # 컬럼 이름들
df.head()

# 스트리밍 수, 차트 잔류 주 수 통계 확인
print(df["streams"].describe())
print(df["weeks_on_chart"].describe())

"""hit레이블 생성 코드"""

# 1) 로그 변환
df["log_streams"] = np.log10(df["streams"])

df[["streams", "log_streams"]].head()

# 2) log_streams, weeks_on_chart 각각 z-score로 표준화
# 해석 참고 : z-socore이 0보다 큰 경우 평균보다 스트리밍이 많고 차트에 오래 있었음.

df["streams_z"] = (df["log_streams"] - df["log_streams"].mean()) / df["log_streams"].std()
df["weeks_z"]   = (df["weeks_on_chart"] - df["weeks_on_chart"].mean()) / df["weeks_on_chart"].std()

df[["log_streams", "streams_z", "weeks_on_chart", "weeks_z"]].head()

# 3) 두 z-score의 평균으로 hit_score 정의

# 두가지 z-score의 평균으로 메가 히트곡(feat.베스트셀러)을 찾기 위한 레이블 정의

df["hit_score"] = (df["streams_z"] + df["weeks_z"]) / 2

df[["streams_z", "weeks_z", "hit_score"]].head()

"""**그렇다면!!**
어떤 곡들을 hit레이블에 해당시킬건가?

--> 가장 직관적이고 대중적인 ***상위 10%*** 를 메가 히트곡으로 정의. --> hit 레이블에 1로 설정.
"""

# 1) 메가 히트 비율 설정 (상위 15%)
top_ratio = 0.10     # 나중에 0.10, 0.20 등으로 바꿔가며 실험 가능
q = 1 - top_ratio    # 예: 0.85 분위수

# 2) hit_score 기준값(threshold) 계산
threshold = df["hit_score"].quantile(q)

print("=== hit_score 기준 정보 ===")
print(f"상위 비율 (top_ratio): {top_ratio*100:.1f}%")
print(f"사용한 분위수 (q): {q:.2f}")
print(f"hit_score threshold 값: {threshold:.4f}")

# 3) threshold 이상이면 hit=1, 미만이면 hit=0
df["hit"] = (df["hit_score"] >= threshold).astype(int)

# 4) 라벨 개수/비율 확인
print("\n=== hit 라벨 분포(개수) ===")
print(df["hit"].value_counts())

print("\n=== hit 라벨 분포(비율) ===")
print(df["hit"].value_counts(normalize=True))

# 5) hit_score 기준 상위 몇 곡 예시로 확인
print("\n=== hit_score 상위 10곡 예시 ===")
print(
    df[["track_name", "artist_names", "hit_score", "streams", "weeks_on_chart", "hit"]]
    .sort_values("hit_score", ascending=False)
    .head(10)
)

"""hit 레이블이 포함된 학습 준비용 csv파일"""

# 현재 df 전체(원본 + hit_score + hit 포함)를 새 CSV로 저장
output_path = "spotify_top_songs_with_hit.csv"

df.to_csv(output_path, index=False)

print("저장 완료:", output_path)