# -*- coding: utf-8 -*-
"""random_forest_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mozYQyK0y5yv7PkDBdKf4PaGpqSY6ryN

# 드라이브 불러오기
"""

from google.colab import drive
drive.mount('/content/drive')

"""# 라이브러리 불러오기"""

import warnings
warnings.filterwarnings('ignore')

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier

"""# 데이터 불러오기"""

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/spotify_preprocessed.csv")
print(df.shape) #(데이터(곡) 개수, feature 개수)
df.head(5)

"""# 불필요한 변수 제거 및 범주형 변수 변환"""

# 모델에 필요가 없거나 hit에 직접적으로 영향을 주는 변수들 제거
drop_cols = ['track_popularity', 'track_id', 'track_name', 'album_name','artist_name', 'album_type', 'album_id', 'artist_followers', 'artist_genres', 'artist_genres_list', 'album_release_date']

existing_drop_cols = [col for col in drop_cols if col in df.columns]
df = df.drop(columns=existing_drop_cols)

print("Removed columns:", existing_drop_cols)
df.head(5)

"""# Feature / Target 분리 -> Y = hit, X = 기타 feature"""

X = df.drop(columns=['hit'])
Y = df['hit']

"""# Train / Test Split
전체 데이터를 학습용(training set)과 평가용(test set)으로 나눈다.
- training set : 모델이 학습하는 데이터
- test set     : 모델의 일반화 성능(처음 보는 데이터)을 평가하는 데이터
"""

X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y,
    test_size=0.2,      # 데이터의 20%를 테스트 데이터로 분리
    random_state=0,     # 매번 실행해도 같은 방식으로 분리되도록 고정
    stratify=Y
)

"""# Random Forest 모델 정의 및 학습"""

model = RandomForestClassifier(
    n_estimators=200,   # 트리 개수 (기본값 100 → 200으로 조금 증가)
    max_depth=8,       # 과적합 방지
    random_state=0,
    class_weight="balanced"
)

model.fit(X_train, Y_train)

"""# 모델 평가
classification_report에 나오는 항목

- precision = TP / (TP + FP)
→ 'Hit 예측 중 실제 Hit 비율' (오탐 축소 중요)

- recall (sensitivity) = TP / (TP + FN)
→ '실제 Hit 중 모델이 맞춘 비율' (놓침 줄이기 중요)

- f1-score = 2 * (precision * recall) / (precision + recall)
→ precision과 recall의 조화평균 (불균형 클래스에 유용)

- support = 해당 클래스의 샘플 수

confusion matrix 구성요소
- TN: 실제 Not-Hit를 Not-Hit로 맞춘 수
- FP: 실제 Not-Hit를 Hit로 잘못 예측한 수 (false alarm)

- FN: 실제 Hit를 Not-Hit로 놓친 수 (miss)

- TP: 실제 Hit를 Hit로 맞춘 수
"""

#학습된 모델이 테스트 데이터(X_test)를 보고 hit(1) 또는 not-hit(0)을 예측함
pred = model.predict(X_test)

print("=== Classification Report ===")
print(classification_report(Y_test, pred))

print("\n=== Confusion Matrix ===")
print(confusion_matrix(Y_test, pred))   # [[TN, FP], [FN, TP]] 형태로 출력

"""# Feature Importance 계산 및 시각화"""

importance = pd.DataFrame({
    'feature': X.columns,
    'importance': model.feature_importances_
}).sort_values(by='importance', ascending=False)

importance_df = importance.head(20)

plt.figure(figsize=(8,6))
plt.barh(importance_df['feature'], importance_df['importance'])
plt.gca().invert_yaxis()
plt.xlabel('Importance')
plt.title('Feature Importance (Random Forest)')
plt.show()

print("\n=== Feature Importance ===")
print(importance)

"""# 연도별 장르 트렌드 분석"""

# Multi-hot 장르 컬럼만 선택
exclude_cols = ['track_number',	'track_duration_ms',	'explicit',	'artist_popularity',	'album_total_tracks',	'release_year',	'release_month',	'release_quarter', 'followers_log',	'hit']
genre_cols = [col for col in df.columns if col not in exclude_cols and df[col].nunique() == 2]

# 연도별 평균 계산
genre_trend = df.groupby('release_year')[genre_cols].mean()

# Top 5 장르 선택
top10_genres = df[genre_cols].sum().sort_values(ascending=False).head(10).index

plt.figure(figsize=(12,6))
for genre in top10_genres:
    plt.plot(genre_trend.index, genre_trend[genre], label=genre)
plt.xlabel('Year')
plt.ylabel('Genre Ratio')
plt.title('Top 10 Genres Trend by Year')
plt.legend()
plt.show()

print("\n연도별 가장 인기 있는 장르\n")

for year in genre_trend.index:
    top_genre = genre_trend.loc[year].idxmax()
    ratio = genre_trend.loc[year].max()
    print(f"{year}년 → {top_genre} (비중: {ratio:.4f})")

"""# 계절성 분석"""

# 분기별 히트곡 비율
quarter_hit = df.groupby('release_quarter')['hit'].mean()

# x축 레이블 매핑
quarter_labels = {1:'Spring', 2:'Summer', 3:'Fall', 4:'Winter'}

plt.figure(figsize=(6,4))
quarter_hit.plot(kind='bar')
plt.xlabel('Season')
plt.ylabel('Hit Ratio')
plt.title('Hit Ratio by Season')
plt.xticks(ticks=[0,1,2,3], labels=[quarter_labels[q] for q in range(1,5)], rotation=0)
plt.show()

# 계절별 인기 장르
print("\n계절별 인기 장르 Top 5\n")

# 계절(분기)별 장르 평균
season_genre_trend = df.groupby('release_quarter')[genre_cols].mean()

for q in range(1, 5):
    season_name = quarter_labels[q]
    top5 = season_genre_trend.loc[q].sort_values(ascending=False).head(5)

    print(f"{season_name}(분기 {q}) Top 5 장르:")
    print(top5)
    print("-" * 40)