# -*- coding: utf-8 -*-
"""random_forest_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pDe1oeSfKj1YHvaXkwJkzvOH9rQcC5Aj

# 드라이브 불러오기
"""

from google.colab import drive
drive.mount('/content/drive')

"""# 라이브러리 불러오기"""

import warnings
warnings.filterwarnings('ignore')

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier

"""# 데이터 불러오기"""

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/spotify_top_songs_with_hit.csv")
print(df.shape) #(데이터(곡) 개수, feature 개수)
df.head(5)

"""# 불필요한 변수 제거 및 범주형 변수 변환"""

# 모델에 필요가 없거나 hit에 직접적으로 영향을 주는 변수들 제거
drop_cols = ['id', 'artist_names', 'track_name', 'source',
             'weeks_on_chart', 'streams', 'log_streams',
             'streams_z', 'weeks_z', 'hit_score']

existing_drop_cols = [col for col in drop_cols if col in df.columns]
df = df.drop(columns=existing_drop_cols)

print("Removed columns:", existing_drop_cols)


# 범주형 변수 변환

# 1) mode (Major / Minor → 1 / 0)
df['mode'] = df['mode'].map({'Major': 1, 'Minor': 0})

# 2) time_signature ("4 beats" → 4)
df['time_signature'] = df['time_signature'].str.extract(r'(\d+)').astype(int)

# 3) key → One-Hot Encoding
df = pd.get_dummies(df, columns=['key'], prefix='key')


# 남아있는 Feature 출력
print("\n=== 남아 있는 Feature 목록 ===")
print(list(df.columns))
print("\n총 Feature 개수 :", len(df.columns))

"""# Feature / Target 분리 -> Y = hit, X = 기타 feature"""

X = df.drop(columns=['hit'])
Y = df['hit']

"""# Train / Test Split
전체 데이터를 학습용(training set)과 평가용(test set)으로 나눈다.
- training set : 모델이 학습하는 데이터
- test set     : 모델의 일반화 성능(처음 보는 데이터)을 평가하는 데이터
"""

X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y,
    test_size=0.2,      # 데이터의 20%를 테스트 데이터로 분리
    random_state=0     # 매번 실행해도 같은 방식으로 분리되도록 고정
)

"""# Random Forest 모델 정의 및 학습"""

model = RandomForestClassifier(
    n_estimators=200,   # 트리 개수 (기본값 100 → 200으로 조금 증가)
    max_depth=8,       # 과적합 방지
    random_state=0,
    class_weight="balanced"
)

model.fit(X_train, Y_train)

"""# 모델 평가
classification_report에 나오는 항목

- precision = TP / (TP + FP)
→ 'Hit 예측 중 실제 Hit 비율' (오탐 축소 중요)

- recall (sensitivity) = TP / (TP + FN)
→ '실제 Hit 중 모델이 맞춘 비율' (놓침 줄이기 중요)

- f1-score = 2 * (precision * recall) / (precision + recall)
→ precision과 recall의 조화평균 (불균형 클래스에 유용)

- support = 해당 클래스의 샘플 수

confusion matrix 구성요소
- TN: 실제 Not-Hit를 Not-Hit로 맞춘 수
- FP: 실제 Not-Hit를 Hit로 잘못 예측한 수 (false alarm)

- FN: 실제 Hit를 Not-Hit로 놓친 수 (miss)

- TP: 실제 Hit를 Hit로 맞춘 수
"""

#학습된 모델이 테스트 데이터(X_test)를 보고 hit(1) 또는 not-hit(0)을 예측함
pred = model.predict(X_test)

print("=== Classification Report ===")
print(classification_report(Y_test, pred))

print("\n=== Confusion Matrix ===")
print(confusion_matrix(Y_test, pred))   # [[TN, FP], [FN, TP]] 형태로 출력

"""# Feature Importance 계산 및 시각화"""

importance = pd.DataFrame({
    'feature': X.columns,
    'importance': model.feature_importances_
}).sort_values(by='importance', ascending=False)

importance_df = importance.head(20)

plt.figure(figsize=(8,6))
plt.barh(importance_df['feature'], importance_df['importance'])
plt.gca().invert_yaxis()
plt.xlabel('Importance')
plt.title('Feature Importance (Random Forest)')
plt.show()

print("\n=== Feature Importance ===")
print(importance)